name: Deploy static HTML to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5B4D631A63D4FB4A692DFA71C070489 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E9FC01BC73E64129A3D7F99D9A661430 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF6BE23E17B04FEC98CEBE5E28138E50 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lab12pavel'
          slot-name: 'Production'
          package: .
